package com.ced2711.lifetracker.ui.localization

/** Simplified Chinese for the Todo screens: English text as written in the code to its translation. */
internal val zhTodo: Map<String, String> = mapOf(
    "Filter and sort" to "筛选和排序",
    "Manage" to "管理",
    "New category" to "新分类",
    "Past occurrences are not changed." to "已过去的重复不会改动。",
    "Copied when you save" to "保存时复制",
    "Only this one" to "仅这一次",
    "This and future" to "这次及以后",
    "Description" to "内容",
    "Due" to "截止",
    "No date" to "无日期",
    "Never" to "不重复",
    "Daily" to "每天",
    "Weekly" to "每周",
    "Monthly" to "每月",
    "Yearly" to "每年",
    "Until (optional)" to "结束于（可选）",
    "No end" to "一直重复",
    "Taken from the description when empty" to "留空时取自内容",
    "Add a todo" to "添加待办",
    "Search todos" to "搜索待办",
    "Nothing to do yet" to "还没有待办",
    "No todos here" to "这里没有待办",
    "Type above to add your first todo." to "在上方输入，添加第一条待办。",
    "Try another view or clear the filters." to "换个视图，或清除筛选。",
    "Yesterday" to "昨天",
    "Later" to "以后",
    "Title" to "标题",
    "Set a due date to add reminders or repeat the task." to "设置截止日期后才能添加提醒或重复。",
    "Choose This and future to change how the task repeats." to "选择“这次及以后”才能修改重复规则。",
    "Selected file" to "已选文件",
    "Show subtasks" to "显示子任务",
    "Hide subtasks" to "收起子任务",
    "It still has open subtasks." to "它还有未完成的子任务。",
)
