package com.ced2711.lifetracker.ui.vault

import android.app.Activity
import android.content.Intent
import android.os.Bundle
import androidx.fragment.app.Fragment
import androidx.fragment.app.FragmentActivity

/**
 * Uses Fragment's legacy result routing because Fragment 1.2.x rejects the high request codes
 * generated by the modern Activity Result registry on Android 8.
 */
internal class VaultLegacyCredentialFragment : Fragment() {
    private var resultCallback: ((VaultLegacyCredentialResult) -> Unit)? = null
    private var resultBuffer = VaultLegacyCredentialResultBuffer()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        if (savedInstanceState != null) {
            resultBuffer = VaultLegacyCredentialResultBuffer(
                VaultLegacyCredentialMetadata(
                    activeRequestId = savedInstanceState.longOrNull(STATE_ACTIVE_REQUEST_ID),
                    completedRequestId = savedInstanceState.longOrNull(
                        STATE_COMPLETED_REQUEST_ID,
                    ),
                    pendingResult = if (
                        savedInstanceState.containsKey(STATE_PENDING_REQUEST_ID) &&
                        savedInstanceState.containsKey(STATE_PENDING_AUTHENTICATED)
                    ) {
                        VaultLegacyCredentialResult(
                            requestId = savedInstanceState.getLong(STATE_PENDING_REQUEST_ID),
                            authenticated = savedInstanceState.getBoolean(
                                STATE_PENDING_AUTHENTICATED,
                            ),
                        )
                    } else {
                        null
                    },
                ),
            )
        }
    }

    override fun onSaveInstanceState(outState: Bundle) {
        resultBuffer.metadata().let { metadata ->
            metadata.activeRequestId?.let {
                outState.putLong(STATE_ACTIVE_REQUEST_ID, it)
            }
            metadata.completedRequestId?.let {
                outState.putLong(STATE_COMPLETED_REQUEST_ID, it)
            }
            metadata.pendingResult?.let { result ->
                outState.putLong(STATE_PENDING_REQUEST_ID, result.requestId)
                outState.putBoolean(STATE_PENDING_AUTHENTICATED, result.authenticated)
            }
        }
        super.onSaveInstanceState(outState)
    }

    /** Returns false when this exact request is already in flight after configuration change. */
    fun launch(requestId: Long, intent: Intent): Boolean {
        if (!resultBuffer.begin(requestId)) return false
        return try {
            startActivityForResult(intent, CREDENTIAL_REQUEST_CODE)
            true
        } catch (error: Throwable) {
            resultBuffer.abandon(requestId)
            throw error
        }
    }

    fun setResultCallback(callback: (VaultLegacyCredentialResult) -> Unit) {
        resultCallback = callback
        resultBuffer.takePendingResult()?.let(callback)
    }

    fun clearResultCallback() {
        resultCallback = null
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode != CREDENTIAL_REQUEST_CODE) return

        val result = resultBuffer.complete(resultCode == Activity.RESULT_OK) ?: return
        val callback = resultCallback
        if (callback != null) {
            callback(result)
        } else {
            resultBuffer.buffer(result)
        }
    }

    companion object {
        internal const val CREDENTIAL_REQUEST_CODE = 0x5641
        internal const val TAG = "taskledger.vault.legacy_credential"
        private const val STATE_ACTIVE_REQUEST_ID = "active_request_id"
        private const val STATE_COMPLETED_REQUEST_ID = "completed_request_id"
        private const val STATE_PENDING_REQUEST_ID = "pending_request_id"
        private const val STATE_PENDING_AUTHENTICATED = "pending_authenticated"
    }
}

internal data class VaultLegacyCredentialResult(
    val requestId: Long,
    val authenticated: Boolean,
)

internal data class VaultLegacyCredentialMetadata(
    val activeRequestId: Long? = null,
    val completedRequestId: Long? = null,
    val pendingResult: VaultLegacyCredentialResult? = null,
)

/** Pure state holder; only non-sensitive request routing metadata is persisted by the Fragment. */
internal class VaultLegacyCredentialResultBuffer(
    metadata: VaultLegacyCredentialMetadata = VaultLegacyCredentialMetadata(),
) {
    private var activeRequestId = metadata.activeRequestId
    private var completedRequestId = metadata.completedRequestId
    private var pendingResult = metadata.pendingResult

    fun begin(requestId: Long): Boolean {
        if (activeRequestId == requestId || completedRequestId == requestId) return false
        check(activeRequestId == null) { "Another credential request is already in flight." }
        activeRequestId = requestId
        return true
    }

    fun abandon(requestId: Long) {
        if (activeRequestId == requestId) activeRequestId = null
    }

    fun complete(authenticated: Boolean): VaultLegacyCredentialResult? {
        val requestId = activeRequestId ?: return null
        activeRequestId = null
        completedRequestId = requestId
        return VaultLegacyCredentialResult(requestId, authenticated)
    }

    fun buffer(result: VaultLegacyCredentialResult) {
        pendingResult = result
    }

    fun takePendingResult(): VaultLegacyCredentialResult? = pendingResult.also {
        pendingResult = null
    }

    fun metadata(): VaultLegacyCredentialMetadata = VaultLegacyCredentialMetadata(
        activeRequestId = activeRequestId,
        completedRequestId = completedRequestId,
        pendingResult = pendingResult,
    )
}

private fun Bundle.longOrNull(key: String): Long? =
    getLong(key).takeIf { containsKey(key) }

internal fun FragmentActivity.getOrCreateVaultLegacyCredentialFragment():
    VaultLegacyCredentialFragment {
    val manager = supportFragmentManager
    val existing = manager.findFragmentByTag(VaultLegacyCredentialFragment.TAG)
    if (existing != null) return existing as VaultLegacyCredentialFragment

    return VaultLegacyCredentialFragment().also { fragment ->
        manager.beginTransaction()
            .add(fragment, VaultLegacyCredentialFragment.TAG)
            .commitNow()
    }
}
