name: Android checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Make Gradle executable
        run: chmod +x gradlew
      - name: Test and lint standard build
        run: ./gradlew testStandardDebugUnitTest lintStandardDebug
